### ISSUE TITLE
Titles are submitted to YOURLS (mostly) without spaces

### ISSUE THREAD

**Issue by dgw** [aaroneaton/better-yourls#10]
I have a lot of CamelCase link titles in my YOURLS database now.

For example, the post title "New Version of WOT Released" becomes "NewVersionofWOTReleased" when submitted to YOURLS by this plugin.

Oddly enough, some have spaces in rare cases, e.g. "Gdrive Rumors Surface Again" becomes "GdriveRumorsSurface Again".

I want to say this is a result of using `sanitize_title()`, but I haven't been able to definitively trace it to anything.

**Comment by domsammut** [comment]
I believe it's related to this function: [esc_url_raw](https://github.com/ChrisWiegman/Better-YOURLS/blob/develop/classes/class-better-yourls-actions.php#L274). Removing the function results in expected output.

The function appears to be intended for use on actual URL values, not an entire array of arguments [based on the documentation](https://codex.wordpress.org/Function_Reference/esc_url_raw). Perhaps it would be better to sanitize each array value according to the type of data?

**Comment by ChrisWiegman** [comment]
Good point. If time permits I'll actually start getting some code on this stuff in this weekend.

**Comment by dgw** [comment]
Looks like it's solved in 3e6d2f3 / 2.0.1, but I'll hold off on closing until I publish my next post tomorrow or Monday and confirm what happens when its URL is shortened.

**Comment by dgw** [comment]
Fixed in 2.0.1, confirmed just now when I published a post. Thanks!
