### ISSUE TITLE
Editing custom menus can create shortlinks

### ISSUE THREAD

**Issue by dgw** [aaroneaton/better-yourls#14]
Seems most likely to happen when adding a new item to a nav-menu and saving it. Haven't looked too far into this, but it probably has something to do with how menus are stored internally.

The shortened URLs look like, for me (with the `/yyyy/mm/slug-here/` permalink structure), `http://domain.tld/2016/01/1234/`, where `1234` appears to be a revision ID or something like that.

**Comment by ChrisWiegman** [comment]
Thanks for the report on that. I'll take a look into it this weekend. Have the other changes helped you?

**Comment by dgw** [comment]
Excluding post types has been a big help, so many thanks for that! Earlier this month I had a post with a custom keyword input use the auto-generated shortlink instead, but haven't been able to reproduce since. (I also might just stop using custom keywords for most posts because it's tedious to make them up. :P)

Old posts seem to be getting shortlinks generated one way or another, either as I update them with minor changes to adapt to my new theme or as they're visited by crawlers. So I think #5 might be solved. If you want statistics on how many past posts have/haven't had links generated I'd be happy to go in and query the database for you and report back.

**Comment by ChrisWiegman** [comment]
Looking into the OP a bit... I'm afraid I'm not able to replicate the issue but I think it may be due to my workflow. I create a page, which generates the link as appropriate upon save, and then I add it to a menu. As the link is already there nothing is changed. Can you please tell me what I'm getting wrong here?

**Comment by ChrisWiegman** [comment]
I stand corrected. Needed to clear cache and check my link list. I'll have a fix for this in the next release. Thanks for the report.

**Comment by ChrisWiegman** [comment]
Fix pushed. Please let me know if you still see the issue.

**Comment by dgw** [comment]
So far so good. No new shortlinks created when I updated the plugin and then edited a couple menus just now. :+1: Thanks again!
