### ISSUE TITLE
Security Error when using using Bulk Edit

### ISSUE THREAD

**Issue by ghost** [aaroneaton/better-yourls#19]
If I try to use the _Bulk Edit_ tool on a published post with Better YOURLS activated, I get a _Security Error_.

See [https://youtu.be/qf-R3Y7lrHw](https://youtu.be/qf-R3Y7lrHw) for a demonstration from a test site with no other activated plugins and using the Twenty Fifteen theme. Better YOURLS settings were the default ('Use https' and 'Allow Self-signed https Certificate' disabled, no post types excluded.)

If it might be helpful in diagnosing the problem, I also noticed that if I hid the Better YOURLS metabox from the post editor with [WPAUIC](https://en-gb.wordpress.org/plugins/wp-admin-ui-customize/) and tried to update a post I saw the same error.

Many thanks!

**Comment by atdr** [comment]
I'm getting this exact same issue too.

**Comment by ghost** [comment]
I am getting the same 'Security Error' when submitting a Jetpack contact form. Works fine with this plugin disabled.
